// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd9ZebvfOOAkLgC66QdqoCJNcFcpjJCbg',
    appId: '1:259011580425:web:4cd778ca22d4a6968e1ed8',
    messagingSenderId: '259011580425',
    projectId: 'wardrobe-app-19e7e',
    authDomain: 'wardrobe-app.web.app',
    storageBucket: 'wardrobe-app-19e7e.firebasestorage.app',
    measurementId: 'G-EX5F4904X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3VWrSXe5FWrlir-38f_fxgmbwY9PPw0',
    appId: '1:259011580425:android:33ac4cc5eff84b058e1ed8',
    messagingSenderId: '259011580425',
    projectId: 'wardrobe-app-19e7e',
    storageBucket: 'wardrobe-app-19e7e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgonTJELdGcclETWJFrxiGxSNck5g_gY',
    appId: '1:259011580425:ios:5b0a0e6ccbfaef1f8e1ed8',
    messagingSenderId: '259011580425',
    projectId: 'wardrobe-app-19e7e',
    storageBucket: 'wardrobe-app-19e7e.firebasestorage.app',
    androidClientId: '259011580425-ngk92dj5dqvrbn1ieu6quv4pf89rikcv.apps.googleusercontent.com',
    iosClientId: '259011580425-poi6v626jr7hp2o3d00dj06rt24mubn7.apps.googleusercontent.com',
    iosBundleId: 'com.wardrobeapp.wardrobeApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgonTJELdGcclETWJFrxiGxSNck5g_gY',
    appId: '1:259011580425:ios:5b0a0e6ccbfaef1f8e1ed8',
    messagingSenderId: '259011580425',
    projectId: 'wardrobe-app-19e7e',
    storageBucket: 'wardrobe-app-19e7e.firebasestorage.app',
    androidClientId: '259011580425-ngk92dj5dqvrbn1ieu6quv4pf89rikcv.apps.googleusercontent.com',
    iosClientId: '259011580425-poi6v626jr7hp2o3d00dj06rt24mubn7.apps.googleusercontent.com',
    iosBundleId: 'com.wardrobeapp.wardrobeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd9ZebvfOOAkLgC66QdqoCJNcFcpjJCbg',
    appId: '1:259011580425:web:db1a3eeca67120b78e1ed8',
    messagingSenderId: '259011580425',
    projectId: 'wardrobe-app-19e7e',
    authDomain: 'wardrobe-app-19e7e.firebaseapp.com',
    storageBucket: 'wardrobe-app-19e7e.firebasestorage.app',
    measurementId: 'G-VVEP2BRY5L',
  );

}