// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVq-qlxhv8lXCjKRYmG1K9RuxqWqRC2k',
    appId: '1:323501498472:web:fd3214d6dcb708a5559bdd',
    messagingSenderId: '323501498472',
    projectId: 'b-bapp-n0ke4x',
    authDomain: 'b-bapp-n0ke4x.firebaseapp.com',
    storageBucket: 'b-bapp-n0ke4x.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESRjCuTl99f6Y-fAHmzrguMThdmHhlGA',
    appId: '1:323501498472:android:d5f9d94b593bccc7559bdd',
    messagingSenderId: '323501498472',
    projectId: 'b-bapp-n0ke4x',
    storageBucket: 'b-bapp-n0ke4x.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvmXDHtJodAEz7LeKh-2AvViJJy_p9Fi0',
    appId: '1:323501498472:ios:5db2429419fba861559bdd',
    messagingSenderId: '323501498472',
    projectId: 'b-bapp-n0ke4x',
    storageBucket: 'b-bapp-n0ke4x.firebasestorage.app',
    iosBundleId: 'com.wardrobeapp.wardrobeApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmXDHtJodAEz7LeKh-2AvViJJy_p9Fi0',
    appId: '1:323501498472:ios:5db2429419fba861559bdd',
    messagingSenderId: '323501498472',
    projectId: 'b-bapp-n0ke4x',
    storageBucket: 'b-bapp-n0ke4x.firebasestorage.app',
    iosBundleId: 'com.wardrobeapp.wardrobeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDVq-qlxhv8lXCjKRYmG1K9RuxqWqRC2k',
    appId: '1:323501498472:web:c3bba746845ed67c559bdd',
    messagingSenderId: '323501498472',
    projectId: 'b-bapp-n0ke4x',
    authDomain: 'b-bapp-n0ke4x.firebaseapp.com',
    storageBucket: 'b-bapp-n0ke4x.firebasestorage.app',
  );

}